# 1. Data loading

In [113]:
# loading the data from the CSV file

import pandas as pd

df_markets = pd.read_csv("../data/polymarket_data.csv")

print(df_markets.shape)

C:\Users\urban\AppData\Local\Temp\ipykernel_10040\154121254.py:5: DtypeWarning: Columns (4,6,15,17,28,29,36,72,78,79,80,81,82,83,89,92,96,97,106,108,109,112,113,116,124,125,126,129,130,131,132,133,134,135,136,138,139) have mixed types. Specify dtype option on import or set low_memory=False.
  df_markets = pd.read_csv("../data/polymarket_data.csv")

(200000, 140)

In [114]:
# first look at the data

pd.set_option('display.max_columns', None)

df_markets.head()

,id,question,conditionId,slug,twitterCardImage,endDate,category,liquidity,image,icon,description,outcomes,outcomePrices,volume,active,marketType,closed,marketMakerAddress,updatedBy,createdAt,updatedAt,closedTime,mailchimpTag,archived,restricted,volumeNum,liquidityNum,endDateIso,hasReviewedDates,readyForCron,volume24hr,volume1wk,volume1mo,volume1yr,clobTokenIds,comboStatus,fpmmLive,volume1wkAmm,volume1moAmm,volume1yrAmm,volume1wkClob,volume1moClob,volume1yrClob,events,creator,ready,funded,cyom,competitive,pagerDutyNotificationEnabled,approved,rewardsMinSize,rewardsMaxSpread,spread,oneDayPriceChange,oneHourPriceChange,oneWeekPriceChange,oneMonthPriceChange,oneYearPriceChange,lastTradePrice,bestBid,bestAsk,clearBookOnStart,manualActivation,negRiskOther,umaResolutionStatuses,pendingDeployment,deploying,rfqEnabled,holdingRewardsEnabled,feesEnabled,requiresTranslation,feeType,startDate,liquidityAmm,resolutionSource,lowerBound,upperBound,formatType,notificationsEnabled,wideFormat,new,featured,sentDiscord,sponsorImage,categoryMailchimpTag,denominationToken,fee,startDateIso,subcategory,submitted_by,groupItemThreshold,enableOrderBook,orderMinSize,umaBond,umaReward,negRisk,twitterCardLocation,twitterCardLastRefreshed,twitterCardLastValidated,marketGroup,groupItemTitle,resolvedBy,questionID,umaEndDate,umaResolutionStatus,umaEndDateIso,orderPriceMinTickSize,commentsEnabled,disqusThread,volumeAmm,volumeClob,acceptingOrders,automaticallyResolved,secondsDelay,liquidityClob,automaticallyActive,gameStartTime,volume24hrClob,volume24hrAmm,teamAID,teamBID,takerBaseFee,customLiveness,seriesColor,showGmpSeries,showGmpOutcome,makerBaseFee,createdBy,clobRewards,negRiskMarketID,negRiskRequestID,acceptingOrdersTimestamp,feeSchedule,deployingTimestamp,gameId,sportsMarketType,line,eventStartTime,groupItemRange
0,12,Will Joe Biden get Coronavirus before the election?,0xe3b423dfad8c22ff75c9899c4e8176f628cf4ad4caa00481764d320e7415f7a9,will-joe-biden-get-coronavirus-before-the-election,https://polymarket-static.s3.us-east-2.amazonaws.com/polymarket-twitter-card.png,2020-11-04T00:00:00Z,US-current-affairs,0.000000,https://polymarket-upload.s3.us-east-2.amazonaws.com/will-joe-biden-get-coronavirus-before-the-election-5a3d4c3b-0a73-419e-a686-be034d2c73ac.png,https://polymarket-upload.s3.us-east-2.amazonaws.com/will-joe-biden-get-coronavirus-before-the-election-5a3d4c3b-0a73-419e-a686-be034d2c73ac.png,"This is a market on if presidential candidate Joe Biden will test positive for COVID-19 before November 3rd, 2020. This will be defined as Joe publicly announcing - via any medium, including social media - that he has tested positive for COVID-19, or some variation of that statement. If it is in reference to antibodies, or he doesn’t publicly acknowledge it, the market will resolve to No.\nIn the event of ambiguity in terms of the market outcome, the market will be resolved at the sole discretion of the Markets Integrity Committee (MIC).","[""Yes"", ""No""]","[""0"", ""0""]",32257.445115,True,normal,True,0x8BD6C3D7a57D650A1870dd338234f90051fe9918,9.0,2020-10-02T16:10:01.467Z,2024-04-23T00:49:51.620233Z,2020-11-02 16:31:01+00,3917403.0,False,False,32257.45,0.00,2020-11-04,True,True,0.0,0.0,0.0,0.0,"[""53135072462907880191400140706440867753044989936304433583131786753949599718775"", ""60869871469376321574904667328762911501870754872924453995477779862968218702336""]",disabled,True,0.0,0.0,0.0,0.0,0.0,0.0,"[{'id': '4690', 'ticker': 'will-joe-biden-get-coronavirus-before-the-election', 'slug': 'will-joe-biden-get-coronavirus-before-the-election', 'title': 'Will Joe Biden get Coronavirus before the election?', 'description': 'This is a market on if presidential candidate Joe Biden will test positive for COVID-19 before November 3rd, 2020. This will be defined as Joe publicly announcing - via any medium, including social media - that he has tested positive for COVID-19, or some variation of that statement. If it is in reference to antibodies, or he doesn’t publicly acknowledge it, the market will resolve to No.\nIn the event of ambiguity in terms of the market outcome, the market will be resolved at the sole discretion of the Markets Integrity Committee (MIC).', 'startDate': '2020-10-02T00:00:00Z', 'creationDate': '2020-10-02T00:00:00Z', 'endDate': '2020-11-04T00:00:00Z', 'image': 'https://polymarket-upload.s3.us-east-2.amazonaws.com/will-joe-biden-get-coronavirus-before-the-election-69e1dbcd-3cfe-4caf-b2af-c00e9ce7186f.png', 'icon': 'https://polymarket-upload.s3.us-east-2.amazonaws.com/will-joe-biden-get-coronavirus-before-the-election-69e1dbcd-3cfe-4caf-b2af-c00e9ce7186f.png', 'active': True, 'closed': True, 'archived': False, 'featured': False, 'restricted': False, 'liquidity': 0, 'volume': 32257.45, 'openInterest': 0, 'sortBy': 'ascending', 'category': 'US-current-affairs', 'published_at': '2022-07-27 14:41:12.085+00', 'createdAt': '2022-07-27T14:41:12.088Z', 'updatedAt': '2024-04-25T18:57:18.376169Z', 'competitive': 0, 'volume24hr': 0, 'volume1wk': 0, 'volume1mo': 0, 'volume1yr': 0, 'liquidityAmm': 0, 'liquidityClob': 0, 'commentCount': 0, 'cyom': False, 'closedTime': '2022-07-27T14:41:12.088Z', 'showAllOutcomes': False, 'showMarketImages': True, 'enableNegRisk': False, 'negRiskAugmented': False, 'pendingDeployment': False, 'deploying': False, 'requiresTranslation': False}]",NaN,False,False,False,0.0,False,True,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,True,False,False,[],False,False,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,17,"Will Airbnb begin publicly trading before Jan 1, 2021?",0x44f10d1cd5aaed4b7ae0b5edb76790f54f45dc0bcaa86831c83d865c774fbb90,will-airbnb-begin-publicly-trading-before-jan-1-2021,https://polymarket-static.s3.us-east-2.amazonaws.com/polymarket-twitter-card.png,2021-01-02T00:00:00Z,Tech,0.000000,https://polymarket-upload.s3.us-east-2.amazonaws.com/will-airbnb-begin-publicly-trading-before-jan-1-2021-c1ba5f2f-c025-486a-9664-15cd8d4ac91b.png,https://polymarket-upload.s3.us-east-2.amazonaws.com/will-airbnb-begin-publicly-trading-before-jan-1-2021-c1ba5f2f-c025-486a-9664-15cd8d4ac91b.png,"This market is on whether or not Airbnb will be a publicly traded company by January 1, 2021. This market will resolve to Yes if Airbnb starts publicly trading on NASDAQ or NYSE before January 1st 2021, regardless of if they list via IPO, direct listing, or some other method. If they are not listed and publicly trading on one of those 2 stock exchanges, the market will resolve to ""No"". In the event of ambiguity in terms of the market outcome, the market will be resolved at the sole discretion of the Markets Integrity Committee (MIC).\n","[""Yes"", ""No""]","[""0"", ""0""]",89665.252158,True,normal,True,0x3d3dB3BeE80414717e3C66c341EF95eCc9BDDBaB,3.0,2020-10-02T19:20:04.234Z,2024-04-23T00:31:22.863043Z,2020-12-11 20:53:24+00,NaN,False,False,89665.25,0.00,2021-01-02,True,True,0.0,0.0,0.0,0.0,"[""23957885615115430922384185661294483989521212430808224513177413172438775950057"", ""44065917169138815451032058926556960033374557137879250075091545322436931840853""]",disabled,True,0.0,0.0,0.0,0.0,0.0,0.0,"[{'id': '3917', 'ticker': 'will-airbnb-begin-publicly-trading-before-jan-1-2021', 'slug': 'will-airbnb-begin-publicly-trading-before-jan-1-2021', 'title': 'Will Airbnb begin publicly trading before Jan 1, 2021?', 'description': 'This market is on whether or not Airbnb will be a publicly traded company by January 1, 2021. This market will resolve to Yes if Airbnb starts publicly trading on NASDAQ or NYSE before January 1st 2021, regardless of if they list via IPO, direct listing, or some other method. If they are not listed and publicly trading on one of those 2 stock exchanges, the market will resolve to ""No"". In the event of ambiguity in terms of the market outcome, the market will be resolved at the sole discretion of the Markets Integrity Committee (MIC).\n', 'startDate': '2020-10-02T00:00:00Z', 'creationDate': '2020-10-02T00:00:00Z', 'endDate': '2021-01-02T00:00:00Z', 'image': 'https://polymarket-upload.s3.us-east-2.amazonaws.com/will-airbnb-begin-publicly-trading-before-jan-1-2021-1767f08a-6651-42b2-9527-73f7be08fd08.png', 'icon': 'https://polymarket-upload.s3.us-east-2.amazonaws.com/will-airbnb-begin-publicly-trading-before-jan-1-2021-1767f08a-6651-42b2-9527-73f7be08fd08.png', 'active': True, 'closed': True, 'archived': False, 'featured': False, 'restricted': False, 'liquidity': 0, 'volume': 89665.25, 'openInterest': 0, 'sortBy': 'ascending', 'category': 'Tech', 'published_at': '2022-07-27 14:40:42.971+00', 'createdAt': '2022-07-27T14:40:42.974Z', 'updatedAt': '2024-04-23T22:47:12.642921Z', 'competitive': 0, 'volume24hr': 0, 'volume1wk': 0, 'volume1mo': 0, 'volume1yr': 0, 'liquidityAmm': 0, 'liquidityClob': 0, 'commentCount': 0, 'cyom': False, 'closedTime': '2022-07-27T14:40:42.974Z', 'showAllOutcomes': False, 'showMarketImages': True, 'enableNegRisk': False, 'negRiskAugmented': False, 'pendingDeployment': False, 'deploying': False, 'requiresTranslation': False}]",NaN,False,False,False,0.0,False,True,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,True,False,False,[],False,False,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,18,"Will a new Supreme Court Justice be confirmed before Nov 3rd, 2020?",0x3e0524de013d9dc359f5eb370773f25de2f03d3200294cfd0fa7dac2f399d101,will-a-new-supreme-court-justice-be-confirmed-before-nov-3rd-2020,https://polymarket-static.s3.us-east-2.amazonaws.com/polymarket-twitter-card.png,2020-11-04T00:00:00Z,US-current-affairs,0.000000,https://polymarket-upload.s3.us-east-2.amazonaws.com/will-a-new-supreme-court-justice-be-confirmed-before-nov-3rd-2020-9799dac2-a822-41bf-909a-cdc8eee8ec3e.png,https://polymarket-upload.s3.us-east-2.amazonaws.com/will-a-new-supreme-court-justice-be-confirmed-before-nov-3rd-2020-9799dac2-a822-41bf-909a-cdc8eee8ec3e.png,"This is a market on whether or not a new Supreme Court Justice will be both nominated and confirmed before Nov 3rd, 2020. Nominated and Confirmed, in the context of the Supreme Court, are defined here: https://en.wikipedia.org/wiki/Appointment_and_confirmation_to_the_Supreme_Court_of_the_United_States. If a Supreme Court Justice is Nominated but not Confirmed before the election, the market will resolve to “No”. RIP RBG. In the event of ambiguity in terms of the market outcome, the market will be resolved at the sole discretion of the Markets Integrity Committee (MIC).","[""Yes"", ""No""]","[""0"", ""0""]",43279.456005,True,normal,True,0x01a4333b6aCb5091cF0219646f35E289546F4656,9.0,2020-10-02T19:20:04.234Z,2024-04-22T23:52:06.957229Z,2020-10-27 00:40:55+00,3917431.0,False,False,43279.46,0.00,2022-01-27,True,True,0.0,0.0,0.0,0.0,"[""7192973530925903015287004813226256961086727269646918334118953338356315960259"", ""16847315704461293231139078524698349110433698045131366205472540524863290566139""]",disabled,True,0.0,0.0,0.0,0.0,0.0,0.0,"[{'id': '5098', 'ticker': 'will-a-new-supreme-court-justice-be-confirmed-before-nov-3rd-2020', 'slug': 'will-a-new-supreme-court-justice-be-confirmed-before-nov-3rd-2020', 'title': 'Will a new Supreme Court Justice be confirmed before Nov 3rd, 2020?', 'description': 'This is a market on whether or not a new Supreme Court Justice will be both nominated and confirmed before Nov 3rd, 2020. Nominated and Confirmed, in the context of the Supreme Court, are defined here: https://en.wikipedia.org/wiki/Appointment_and_confirmation_to_the_Supreme_Court_of_the_United_States. If a Supreme Court Justice is Nominated but not Confirmed before the election, the market will resolve to “No”. RIP RBG. In the event of ambiguity in terms of the market outcome, the market will be resolved at the sole discretion of the Markets Integrity Committee (MIC).', 'startDate': '2020-10-02T00:00:00Z', 'creationDate': '2020-10-02T00:00:00Z', 'endDate': '2022-01-27T00:00:00Z', 'image': 'https://polymarket-upload.s3.us-east-2.amazonaws.com/will-a-new-supreme-court-justice-be-confirmed-before-nov-3rd-2020-3c76e3ef-bf2f-4ca3-962b-fed3155516e8.png', 'icon': 'https://polymarket-upload.s3.us-east-2.amazonaws.com/will-a-new-supreme-court-justice-be-confirmed-before-nov-3rd-2020-3c76e3ef-bf2f-4ca3-962b-fed3155516e8.png', 'active': True, 'closed': True, 'archived': False, 'featured': False, 'restricted': False, 'liquidity': 0, 'volume': 43279.46, 'openInterest': 0, 'sortBy': 'ascending', 'category': 'US-current-affairs', 'published_at': '2022-07-27 14:41:27.361+00', 'createdAt': '2022-07-27T14:41:27.364Z', 'updatedAt': '2024-04-25T18:56:11.18445Z', 'competitive': 0, 'volume24hr': 0, 'volume1wk': 0, 'volume1mo': 0, 'volume1yr': 0, 'liquidityAmm': 0, 'liquidityClob': 0, 'commentCount': 0, 'cyom': False, 'closedTime': '2022-07-27T14:41:27.364Z', 'showAllOutcomes': False, 'showMarketImages': True, 'enableNegRisk': False, 'negRiskAugmented': False, 'pendingDeployment': False, 'deploying': False, 'requiresTranslation': False}]",NaN,False,False,False,0.0,False,True,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,True,False,False,[],False,False,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,19,"Will Kim Kardashian and Kanye West divorce before Jan 1, 2021?",0x9b946f54f3428aafc308c33aa04a943fe13a011bdac9a9b66e1ba16c416ca256,will-kim-kardashian-and-kanye-west-divorce-before-jan-1-2021,https://polymarket-static.s3.us-east-2.amazonaws.com/polymarket-twitter-card.png,2021-01-02T00:00:00Z,Pop-Culture,0.179651,https://polymarket-upload.s3.us-east-2.amazonaws.com/will-kim-kardashian-and-kanye-west-divorce-before-jan-1-2021-56c39e78-0a04-4827-bf52-d2c1052f82d9.png,https://polymarket-upload.s3.us-east-2.amazonaws.com/will-kim-kardashian-and-kanye-west-divorce-before-jan-1-2021-56c39e78-0a04-4827-bf52-d2c1052f82d9.png,"This is a market on whether Kanye West and Kim Kardashian will officially file for a divorce before January 1st 2021. Divorce can be defined empirically as either an official announcement direct from either Kim or Kanye, or an official filing of divorce, including but not limited to certified copies of divorce decrees available from the Superior Court in the county where the decree was granted. This market will resolve ""Yes"" if the aforementioned conditions are met and ""No"" otherwise. In the event of ambiguity in terms of the market outcome, the market will be resolved at the sole discretion of the Markets Integrity Committee (MIC).\n","[""Yes"", ""No""]","[""0.000001011082052522541417308141468657552"", ""0.9999989889179474774585826918585313""]",22067.475119,True,normal,True,0x13064324dFF1e76062975345d255EFccc6C78bd0,126.0,2020-10-02T19:20:04.234Z,2024-04-26T02:45:04.309477Z,2021-01-02 21:35:34+00,4102440.0,False,False,22067.48,0.18,2021-01-02,True,True,0.0,0.0,0.0,0.0,"[""4485468797843270805361907688585033105060134197906764657766452761383944608702"", ""99620935296034450526138833612193162137893979576079468831519296537203486531810""]",disabled,True,0.0,0.0,0.0,0.0,0.0,0.0,"[{'id': '4870', 'ticker': 'will-kim-kardashian-and-kanye-west-divorce-before-jan-1-2021', 'slug': 'will-kim-kardashian-and-kanye-west-divorce-before-jan-1-2021', 'title': 'Will Kim Kardashian and Kanye West divorce before Jan 1, 2021?', 'description': 'This is a market on whether Kanye West and Kim Kardashian will officially file for a divorce before January 1st 2021. Divorce can be defined empirically as either an official announcement direct from either Kim or Kanye, or an official filing of divorce, including but not limited to certified copies of divorce decrees available from the Superior Court in the county where the decree was granted. This market will resolve ""Yes"" if the aforementioned conditions are met and ""No"" otherwise. In the event of ambiguity in terms of the market outcome, the market will be resolved at the sole discretion of the Markets Integrity Committee (MIC).\n', 'startDate': '2020-10-02T00:00:00Z', 'creationDate': '2020-10-02T00:00:00Z', 'endDate': '2021-01-02T00:00:00Z', 'image': 'https://polymarket-upload.s3.us-east-2.amazonaws.com/will-kim-kardashian-and-kanye-west-divorce-before-jan-1-2021-72891edd-88ea-41fb-86ac-7623838d49b0.png', 'icon': 'https://polymarket-upload.s3.us-east-2.amazonaws.com/will-kim-kardashian-and-kanye-west-divorce-before-jan-1-2021-72891edd-88ea-41fb-86ac-7623838d49b0.png', 'active': True, 'closed': True, 'archived': False, 'featured': False, 'restricted': False, 'liquidity': 0, 'volume': 22067.48, 'openInterest': 0, 'sortBy': 'ascending', 'category': 'Pop-Culture ', 'published_at': '2022-07-27 14:41:18.863+00', 'createdAt': '2022-07-27T14:41:18.866Z', 'updatedAt': '2024-04-25T19:57:53.317939Z', 'competitive': 0, 'volume24hr': 0, 'volume1wk': 0, 'volume1mo': 0, 'volume1yr': 0, 'liquidityAmm': 0, 'liquidityClob': 0, 'commentCount': 0, 'cyom': False, 'closedTime': '2022-07-27T14:41:18.866Z', 'showAllOutcomes': False, 'showMarketImages': True, 'enableNegRisk': False, 'negRiskAugmented': False, 'pendingDeployment': False, 'deploying': False, 'requiresTranslation': False}]",NaN,False,False,False,0.0,False,True,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,True,False,False,[],False,False,False,False,False,False,NaN,2023-08-24T16:35:24.938Z,0.18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# 2. Get a smaller dataframe with less columns

In [115]:
# create a smaller DataFrame with only the important columns

important_cols = [
    "id",
    "question",
    "startDateIso",
    "endDateIso",
    "volume",
    "liquidity",
    "outcomes",
    "outcomePrices",
    "requiresTranslation",
    "feeType",
    "rewardsMinSize",
    "restricted",
    "marketType",
    "spread",
    "bestBid",
    "bestAsk",
    "active",
    "closed",
    "category"
]

df_markets_small = df_markets[important_cols].copy()

# check the size of the new DataFrame
print(df_markets_small.shape)

# check the first rows of the new DataFrame
df_markets_small.head()

(200000, 19)

,id,question,startDateIso,endDateIso,volume,liquidity,outcomes,outcomePrices,requiresTranslation,feeType,rewardsMinSize,restricted,marketType,spread,bestBid,bestAsk,active,closed,category
0,12,Will Joe Biden get Coronavirus before the election?,NaN,2020-11-04,32257.445115,0.000000,"[""Yes"", ""No""]","[""0"", ""0""]",False,NaN,0.0,False,normal,1.0,0.0,1.0,True,True,US-current-affairs
1,17,"Will Airbnb begin publicly trading before Jan 1, 2021?",NaN,2021-01-02,89665.252158,0.000000,"[""Yes"", ""No""]","[""0"", ""0""]",False,NaN,0.0,False,normal,1.0,0.0,1.0,True,True,Tech
2,18,"Will a new Supreme Court Justice be confirmed before Nov 3rd, 2020?",NaN,2022-01-27,43279.456005,0.000000,"[""Yes"", ""No""]","[""0"", ""0""]",False,NaN,0.0,False,normal,1.0,0.0,1.0,True,True,US-current-affairs
3,19,"Will Kim Kardashian and Kanye West divorce before Jan 1, 2021?",NaN,2021-01-02,22067.475119,0.179651,"[""Yes"", ""No""]","[""0.000001011082052522541417308141468657552"", ""0.9999989889179474774585826918585313""]",False,NaN,0.0,False,normal,1.0,0.0,1.0,True,True,Pop-Culture
4,20,"Will Coinbase begin publicly trading before Jan 1, 2021?",NaN,2021-01-02,116803.377183,0.367501,"[""Yes"", ""No""]","[""0.000001024519509568169644816863666886675"", ""0.9999989754804904318303551831363331""]",False,NaN,0.0,False,normal,1.0,0.0,1.0,True,True,Crypto

In [116]:
# check the info of the new DataFrame

df_markets_small.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 19 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   id                   200000 non-null  int64
 1   question             200000 non-null  object
 2   startDateIso         193809 non-null  object
 3   endDateIso           198222 non-null  object
 4   volume               182492 non-null  float64
 5   liquidity            65287 non-null   float64
 6   outcomes             200000 non-null  object
 7   outcomePrices        200000 non-null  object
 8   requiresTranslation  200000 non-null  bool
 9   feeType              1834 non-null    object
 10  rewardsMinSize       200000 non-null  float64
 11  restricted           200000 non-null  bool
 12  marketType           10099 non-null   object
 13  spread               200000 non-null  float64
 14  bestBid              92731 non-null   float64
 15  bestAsk              200000 non-null  float64
 16  active               200000 non-null  bool
 17  closed               200000 non-null  bool
 18  category             4367 non-null    object
dtypes: bool(4), float64(6), int64(1), object(8)
memory usage: 23.7+ MB

In [117]:
# drop variables with not enough entries

df_markets_small.drop(columns=["feeType", "marketType", "category"], inplace=True)

# test 
print("Number of columns:", df_markets_small.shape[1])

Number of columns: 16

# 3. Get a first look at the variables

In [118]:
# check the value counts of the "active" column

df_markets_small["active"].value_counts()

active
True    200000
Name: count, dtype: int64

In [119]:
# drop the "active" column because every market is active and it doesn't provide any useful information

df_markets_small.drop(columns=["active"], inplace=True)

In [120]:
# check the value counts of the "closed" column

df_markets_small["closed"].value_counts()

closed
True    200000
Name: count, dtype: int64

In [121]:
# drop the "closed" column because every market is closed and it doesn't provide any useful information

df_markets_small.drop(columns=["closed"], inplace=True)

In [122]:
# check the time period

# convert to datetime
df_markets_small["startDateIso"] = pd.to_datetime(df_markets_small["startDateIso"])
df_markets_small["endDateIso"] = pd.to_datetime(df_markets_small["endDateIso"])

# min and max
print("StartDateIso")
print("Min:", df_markets_small["startDateIso"].min())
print("Max:", df_markets_small["startDateIso"].max())

print("\nEndDateIso")
print("Min:", df_markets_small["endDateIso"].min())
print("Max:", df_markets_small["endDateIso"].max())

StartDateIso
Min: 2021-01-25 00:00:00
Max: 2026-04-10 00:00:00

EndDateIso
Min: 2002-07-26 00:00:00
Max: 2027-01-01 00:00:00

In [123]:
# polymarket was launched in 2020, so there shouldnt be any markets before 2020 (https://startpolymarket.com/learn/polymarket-company/)

# count markets ending before June 1, 2020
count = (df_markets_small["endDateIso"] < "2020-06-01").sum()

print(count)

3

In [124]:
# have a look at those markets

df_markets_small.loc[
    df_markets_small["endDateIso"] < "2020-06-01",
    ["question", "startDateIso", "endDateIso"]
]

,question,startDateIso,endDateIso
495,Will any NBA Conference Semifinal Series go to a Game 7?,NaT,2018-06-13
583,Will the Suns or Clippers win the 2021 NBA Western Conference Finals?,NaT,2002-07-26
661,Will the Canadiens or Lightning win the Stanley Cup Finals?,NaT,2011-07-05

In [125]:
# these entries are wrong so we drop these entries (not the whole market)

df_markets_small.loc[
    df_markets_small["endDateIso"] < "2020-06-01",
    "endDateIso"
] = pd.NaT

# test
print("Number of entries with wrong endDateIso:", (df_markets_small["endDateIso"] < "2020-06-01").sum())
print("Markets:", len(df_markets_small))

Number of entries with wrong endDateIso: 0
Markets: 200000

In [126]:
# number of markets where endDateIso < startDateIso
count_invalid_dates = (
    df_markets_small["endDateIso"] < df_markets_small["startDateIso"]
).sum()

print("Number of problematic rows:", count_invalid_dates)

Number of problematic rows: 286

In [127]:
# look at the problematic rows

df_markets_small.loc[
    df_markets_small["endDateIso"] < df_markets_small["startDateIso"],
    ["question", "startDateIso", "endDateIso"]
].head(50)

,question,startDateIso,endDateIso
248,"Will Benjamin Netanyahu remain prime minister of Israel through June 30, 2021?",2026-04-10,2021-06-30
1049,Will Atletico Madrid or Liverpool win their Champions League match on October 19th?,2021-10-19,2021-10-18
1567,Will it snow in New York's Central Park on New Year's Eve (Dec 31)?,2025-11-20,2022-01-01
2240,NHL: Will the Lightning beat the Canucks by more than 1.5 goals in their January 13 matchup?,2022-01-14,2022-01-13
2241,NHL: Will the Islanders beat the Devils by more than 1.5 goals in their January 13 matchup?,2022-01-14,2022-01-13
2242,NHL: Will the Predators beat the Sabres by more than 1.5 goals in their January 13 matchup?,2022-01-14,2022-01-13
2243,NHL: Will the Blues beat the Kraken by more than 1.5 goals in their January 13 matchup?,2022-01-14,2022-01-13
2244,NHL: Will the Blackhawks beat the Canadiens by more than 1.5 goals in their January 13 matchup?,2022-01-14,2022-01-13
2245,NHL: Will the Flames beat the Senators by more than 1.5 goals in their January 13 matchup?,2022-01-14,2022-01-13
2246,NHL: Will the Rangers beat the Sharks by more than 1.5 goals in their January 13 matchup?,2022-01-14,2022-01-13
2247,NHL: Will the Penguins beat the Kings by more than 1.5 goals in their January 13 matchup?,2022-01-14,2022-01-13
2248,NHL: Will the Jets beat the Red Wings by more than 1.5 goals in their January 13 matchup?,2022-01-14,2022-01-13
2318,NBA: Will the Warriors beat the Pistons by more than 14.5 points in their January 18 matchup?,2022-01-19,2022-01-18
5065,NBA: Jazz vs. Raptors (02/10/2023),2023-02-10,2023-02-06
5066,NBA: Rockets vs. Heat (02/10/2023),2023-02-10,2023-02-06
5067,NBA: Timberwolves vs. Grizzlies (02/10/2023),2023-02-10,2023-02-06
5068,NBA: Thunder vs. Trail Blazers (02/10/2023),2023-02-10,2023-02-06
5069,NBA: Cavaliers vs. Pelicans (02/10/2023),2023-02-10,2023-02-06
5070,NBA: Mavericks vs. Kings (02/10/2023),2023-02-10,2023-02-06
5071,NBA: Bucks vs. Clippers (02/10/2023),2023-02-10,2023-02-07
5075,NBA: Spurs vs. Cavaliers (02/13/2023),2023-02-13,2023-02-12
5076,NBA: Jazz vs. Pacers (02/13/2023),2023-02-13,2023-02-12
5077,NBA: Rockets vs. 76ers (02/13/2023),2023-02-13,2023-02-12
5078,NBA: Nuggets vs. Heat (02/13/2023),2023-02-13,2023-02-12
5079,NBA: Nets vs. Knicks (02/13/2023),2023-02-13,2023-02-12
5080,NBA: Magic vs. Bulls (02/13/2023),2023-02-13,2023-02-12
5081,NBA: Pelicans vs. Thunder (02/13/2023),2023-02-13,2023-02-12
5082,NBA: Timberwolves vs. Mavericks (02/13/2023),2023-02-13,2023-02-12
5083,NBA: Lakers vs. Trail Blazers (02/13/2023),2023-02-13,2023-02-12
5084,NBA: Wizards vs. Warriors (02/13/2023),2023-02-13,2023-02-12
5120,NBA: Spurs vs. Hornets (02/15/2023),2023-02-15,2023-02-12
5121,NBA: Bulls vs. Pacers (02/15/2023),2023-02-15,2023-02-12
5122,NBA: Cavaliers vs. 76ers (02/15/2023),2023-02-15,2023-02-12
5123,NBA: Knicks vs. Hawks (02/15/2023),2023-02-15,2023-02-12
5124,NBA: Heat vs. Nets (02/15/2023),2023-02-15,2023-02-12
5125,NBA: Pistons vs. Celtics (02/15/2023),2023-02-15,2023-02-12
5126,NBA: Jazz vs. Grizzlies (02/15/2023),2023-02-15,2023-02-12
5127,NBA: Rockets vs. Thunder (02/15/2023),2023-02-15,2023-02-12
5128,NBA: Mavericks vs. Nuggets (02/15/2023),2023-02-15,2023-02-12
5129,NBA: Pelicans vs. Lakers (02/15/2023),2023-02-15,2023-02-12
5155,Will another flying object be downed by the U.S. on February 16?,2023-02-16,2023-02-15
5190,NBA: Indiana Pacers vs. Boston Celtics 2023-02-23,2023-02-23,2023-02-22
5191,NBA: Orlando Magic vs. Detroit Pistons 2023-02-23,2023-02-23,2023-02-22
5192,NBA: Cleveland Cavaliers vs. Denver Nuggets 2023-02-23,2023-02-23,2023-02-22
5193,NBA: Toronto Raptors vs. New Orleans Pelicans 2023-02-23,2023-02-23,2023-02-22
5194,NBA: Philadelphia 76ers vs. Memphis Grizzlies 2023-02-23,2023-02-23,2023-02-22
5195,NBA: Dallas Mavericks vs. San Antonio Spurs 2023-02-23,2023-02-23,2023-02-22
5196,NBA: Utah Jazz vs. Oklahoma City Thunder 2023-02-23,2023-02-23,2023-02-22
5197,NBA: Los Angeles Lakers vs. Golden State Warriors 2023-02-23,2023-02-23,2023-02-22
5198,NBA: Sacramento Kings vs. Portland Trail Blazers 2023-02-23,2023-02-23,2023-02-22

In [128]:
# check the distribution of requiresTranslation

df_markets_small["requiresTranslation"].value_counts()

requiresTranslation
False    200000
Name: count, dtype: int64

In [129]:
# drop the "requiresTranslation" column because every market has the same value and it doesn't provide any useful information

df_markets_small.drop(columns=["requiresTranslation"], inplace=True)

In [130]:
# How many markets end before today?

# Count rows with endDateIso before today
count = (df_markets_small["endDateIso"] < pd.Timestamp.today()).sum()

print(count)

196870

In [131]:
# How many markets end after today?

# Count rows with endDateIso after today
count = (df_markets_small["endDateIso"] > pd.Timestamp.today()).sum()

print(count)

1349

In [132]:
# check the distribution of rewardsMinSize

df_markets_small["rewardsMinSize"].value_counts()

rewardsMinSize
0.0        152661
20.0        18079
50.0        15955
100.0        9915
200.0        3117
10.0          106
40.0           56
5.5            27
30.0           26
500.0          15
25.0            9
60.0            7
5.0             7
59.0            5
400.0           4
150.0           3
10000.0         2
15.0            1
199.0           1
550.0           1
1010.0          1
2200.0          1
4.5             1
Name: count, dtype: int64

In [133]:
# check markets that are still open and have a rewardsMinSize > 1

# Filter conditions
filtered_df = df_markets_small[
    (df_markets_small["endDateIso"] > pd.Timestamp.today()) &
    (df_markets_small["rewardsMinSize"] > 1)
]

# Show first rows
filtered_df.head()

,id,question,startDateIso,endDateIso,volume,liquidity,outcomes,outcomePrices,rewardsMinSize,restricted,spread,bestBid,bestAsk
25333,517427,Will Israel annex Lebanese territory before July?,2025-01-15,2026-06-30,3.259151e+04,NaN,"[""Yes"", ""No""]","[""0"", ""1""]",50.0,True,0.001,NaN,0.001
25334,517428,Will Israel annex Syrian territory before July?,2025-01-15,2026-06-30,1.328292e+05,NaN,"[""Yes"", ""No""]","[""0"", ""1""]",50.0,True,0.001,NaN,0.001
52520,549621,Will the Party for Freedom win the most seats in the 2025 Netherlands parliamentary election?,2025-06-03,2026-07-31,1.014755e+07,NaN,"[""Yes"", ""No""]","[""0"", ""1""]",200.0,True,0.001,NaN,0.001
52521,549622,Will GreenLeft–Labour win the most seats in the 2025 Netherlands parliamentary election?,2025-06-03,2026-07-31,1.679680e+06,NaN,"[""Yes"", ""No""]","[""0"", ""1""]",200.0,True,0.001,NaN,0.001
52522,549623,Will People's Party for Freedom and Democracy win the most seats in the 2025 Netherlands parliamentary election?,2025-06-03,2026-07-31,2.826083e+06,NaN,"[""Yes"", ""No""]","[""0"", ""1""]",100.0,True,0.001,NaN,0.001

In [134]:
# check the distribution of restricted

df_markets_small["restricted"].value_counts()

restricted
True     198026
False      1974
Name: count, dtype: int64

In [135]:
# convert restricted to int (0 and 1)

df_markets_small["restricted"] = (
    df_markets_small["restricted"]
    .astype(int)
)

# Test
df_markets_small["restricted"].value_counts()

restricted
1    198026
0      1974
Name: count, dtype: int64

In [136]:
# check the distribution of outcomes

df_markets_small["outcomes"].value_counts()

outcomes
["Yes", "No"]                                                         103898
["Up", "Down"]                                                         42477
["Over", "Under"]                                                      15690
["Favorite", "Underdog"]                                                 561
["Long", "Short"]                                                         71
                                                                       ...
["SKA St. Petersburg", "Amur Khabarovsk"]                                  1
["Trinec", "Mlada Boleslav"]                                               1
["Lada Togliatti", "Severstal Cherepovets"]                                1
["Mississippi Valley State Delta Devils", "Kansas State Wildcats"]         1
["Lafayette Leopards", "Penn Quakers"]                                     1
Name: count, Length: 18958, dtype: int64

In [137]:
# How many markets have more than two outcomes?

import ast

int(
    (df_markets_small["outcomes"]
     .apply(lambda x: len(ast.literal_eval(x)) if pd.notna(x) else None)
     > 2).sum()
)

40

In [138]:
# check the distribution of outcomePrices

df_markets_small["outcomePrices"].value_counts()

outcomePrices
["0", "1"]                                                                               123808
["1", "0"]                                                                                70702
["0.5", "0.5"]                                                                              402
["0", "0"]                                                                                  162
["1", "1"]                                                                                   14
                                                                                          ...
["0.00008140065502455539362525619258397161", "0.999918599344975444606374743807416"]           1
["0.9767158039242547230409151207614376", "0.02328419607574527695908487923856237"]             1
["0.9983807150995029586129233822861769", "0.001619284900497041387076617713823074"]            1
["0.0008088022157301320448413746641134995", "0.9991911977842698679551586253358865"]           1
["0.000001024519509568169644816863666886675", "0.9999989754804904318303551831363331"]         1
Name: count, Length: 4915, dtype: int64

In [139]:
# How many markets have more than two outcomePrices?

import ast

int(
    (df_markets_small["outcomePrices"]
     .apply(lambda x: len(ast.literal_eval(x)) if pd.notna(x) else None)
     > 2).sum()
)

40

In [140]:
# have a look at the distribution of the variable volume 

# convert to numeric
df_markets_small["volume"] = pd.to_numeric(
    df_markets_small["volume"],
    errors="coerce"
)


df_markets_small["volume"].describe()

count    1.824920e+05
mean     2.336772e+05
std      5.317336e+06
min      0.000000e+00
25%      1.820869e+03
50%      9.910480e+03
75%      4.619555e+04
max      1.531479e+09
Name: volume, dtype: float64

In [141]:
# Remove markets with missing trading volume
df_markets_small = df_markets_small.dropna(subset=["volume"])

# test
df_markets_small.shape

(182492, 13)

In [142]:
# have a look at the distribution of the variable liquidity

# convert to numeric
df_markets_small["liquidity"] = pd.to_numeric(
    df_markets_small["liquidity"],
    errors="coerce"
)

df_markets_small["liquidity"].describe()

count     48227.000000
mean        188.810067
std        4344.385666
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max      406695.107740
Name: liquidity, dtype: float64

In [143]:
# have a look at the distribution of the variable spread

df_markets_small["spread"].describe()

count    182492.000000
mean          0.145157
std          23.407668
min           0.001000
25%           0.001000
50%           0.001000
75%           0.009000
max        9998.990000
Name: spread, dtype: float64

In [144]:
# have a look at the distribution of the variable bestAsk

df_markets_small["bestAsk"].describe()

count    182492.000000
mean          0.482986
std          23.412432
min          -0.004000
25%           0.001000
50%           0.010000
75%           1.000000
max        9999.990000
Name: bestAsk, dtype: float64

In [145]:
# have a look at the distribution of the variable bestBid

df_markets_small["bestBid"].describe()

count    87338.000000
mean         0.687790
std          0.405995
min         -0.010000
25%          0.320000
50%          0.994000
75%          0.999000
max          1.000000
Name: bestBid, dtype: float64

Interpretation of Prices on Polymarket: A Polymarket share pays $1 if the event occurs and $0 otherwise. Therefore, prices are bounded between 0 and 1 and can be interpreted as market-implied probabilities. 

So prices lower than 0 and higher than 1 are wrong and need to be removed.

In [146]:
# Set invalid bid/ask values (<0 or >1) to NaN

df_markets_small.loc[
    (df_markets_small["bestBid"] < 0) | (df_markets_small["bestBid"] > 1),
    "bestBid"
] = pd.NA

df_markets_small.loc[
    (df_markets_small["bestAsk"] < 0) | (df_markets_small["bestAsk"] > 1),
    "bestAsk"
] = pd.NA

In [147]:
# have another look at the distribution of the variable bestAsk

df_markets_small["bestAsk"].describe()

count    182478.000000
mean          0.428151
std           0.469853
min           0.001000
25%           0.001000
50%           0.010000
75%           1.000000
max           1.000000
Name: bestAsk, dtype: float64

In [148]:
# have another look at the distribution of the variable bestBid

df_markets_small["bestBid"].describe()

count    87337.000000
mean         0.687798
std          0.405990
min          0.000000
25%          0.320000
50%          0.994000
75%          0.999000
max          1.000000
Name: bestBid, dtype: float64

why is the count of spread 200.000 if the count of bestBid is only 92.809?

In [149]:
# check markets where bestBid is NaN

df_markets_small[
    df_markets_small["bestBid"].isna()
][["question", "bestBid", "bestAsk", "spread"]].head(10)

,question,bestBid,bestAsk,spread
1999,[Single Market] Will Joe Biden win the U.S. 2024 Democratic presidential nomination?,NaN,0.001,0.001
2001,[Single Market] Will Pete Buttigieg win the U.S. 2024 Democratic presidential nomination?,NaN,0.005,0.005
2002,[Single Market] Will Hillary Clinton win the U.S. 2024 Democratic presidential nomination?,NaN,0.005,0.005
4221,[Single Market] Will Gavin Newsom win the U.S. 2024 Democratic presidential nomination?,NaN,0.001,0.001
6593,[Single Market] Will Robert F. Kennedy Jr. win the U.S. 2024 Democratic presidential nomination?,NaN,0.003,0.003
7279,Trump and Biden both win nomination?,NaN,0.005,0.005
7712,Senate control after 2024 election?,NaN,0.001,0.001
8104,[Single Market] Will Dean Phillips win the U.S. Democratic presidential nomination?,NaN,0.005,0.005
8440,Will an AI win the $5 million AI Math Olympiad Prize before August?,NaN,0.009,0.009
8453,Will ≥10% of Votes go to 3rd Party Candidates in the 2024 US Presidential Election?,NaN,0.014,0.014

So this spread variable interpret NAN in bestBid as 0. This is wrong because when bestBid is NAN, then there is no bid at all. Therefore I´m creating a new variable spread where NAN is interpreted as NAN and not 0.

# 4. Creating new variables

## 4.1 spread

In [150]:
# before creating a new variable spread, we rename the existing spread variable to "spread_poly" to avoid confusion

df_markets_small.rename(columns={"spread": "spread_poly"}, inplace=True)

# check
df_markets_small.columns

Index(['id', 'question', 'startDateIso', 'endDateIso', 'volume', 'liquidity',
       'outcomes', 'outcomePrices', 'rewardsMinSize', 'restricted',
       'spread_poly', 'bestBid', 'bestAsk'],
      dtype='object')

In [151]:
# create a new variable spread which is the difference between bestAsk and bestBid

df_markets_small["spread"] = (
    df_markets_small["bestAsk"] - df_markets_small["bestBid"]
)

# test if there are as many non-null entrys as in bestBid
df_markets_small["spread"].describe()

count    87324.000000
mean         0.179477
std          0.358407
min         -0.170000
25%          0.001000
50%          0.004000
75%          0.060000
max          1.000000
Name: spread, dtype: float64

## 4.2 categories

creating new dummy variables for categories

| Category | Purpose |
|----------|---------|
| Politics | Political events, elections, governments |
| Sports | Traditional sports events and matches |
| Esports | Competitive gaming and esports |
| Crypto | Cryptocurrencies, blockchain, DeFi |
| Finance | Macroeconomics, stock markets, interest rates |
| Business | Company-specific events, M&A, CEOs |
| Technology / AI | AI, tech products, software, innovation |
| Geopolitics | Wars, conflicts, international relations |
| Culture | Celebrities, movies, music, awards, entertainment |
| Science | Science, climate, weather, health events |

In [152]:
# create a new column "politics" that is 1 if the question contains any of the politics keywords, otherwise 0   

import pandas as pd
import re

# politics keywords
politics_keywords = [
    "trump", "biden", "obama", "clinton", "harris", "desantis",
    "rfk", "kennedy", "vivek", "haley", "pence", "pelosi",
    "schumer", "mcconnell", "putin", "xi", "macron", "modi",
    "erdogan", "zelensky", "netanyahu",

    "election", "elections", "vote", "votes", "voting",
    "ballot", "poll", "polls", "polling", "approval rating",
    "exit poll", "primary", "caucus", "runoff", "referendum",

    "president", "presidential", "vice president", "vp",
    "senate", "senator", "congress", "house", "speaker",
    "governor", "mayor", "parliament", "mp", "prime minister",
    "minister", "cabinet", "government", "administration",

    "democrat", "democratic", "republican", "gop",
    "labour", "conservative", "liberal", "green party",
    "socialist", "communist", "far right", "far left",

    "campaign", "debate", "rally", "nominee", "nomination",
    "inauguration", "reelection", "incumbent",

    "white house", "supreme court", "scotus",
    "executive order", "filibuster", "legislation",
    "bill", "law", "policy", "tax reform", "tariff",
    "immigration", "border", "healthcare", "abortion",
    "gun control", "climate policy",

    "approval", "disapproval", "approval odds",
    "approval rate", "favorability",

    "dictator", "monarchy", "king", "queen",
    "constitution", "constitutional", "democracy",
    "authoritarian", "regime", "sanction", "diplomacy",

    "eu", "european union", "nato", "un", "united nations",
    "brexit"
]

pattern = r"\b(?:" + "|".join(re.escape(word) for word in politics_keywords) + r")\b"

df_markets_small["politics"] = (
    df_markets_small["question"]
    .str.lower()
    .str.contains(pattern, na=False)
    .astype(int)
)

In [153]:
# check the distribution of the new column politics

df_markets_small["politics"].value_counts()

politics
0    167942
1     14550
Name: count, dtype: int64

In [154]:
# create a new column "sports" that is 1 if the question contains any of the sports keywords, otherwise 0

sports_keywords = [

    # General sports terms
    "sports", "sport", "match", "game", "final", "finals",
    "playoff", "playoffs", "tournament", "championship",
    "world cup", "league", "cup", "season", "coach",
    "manager", "athlete", "team", "score", "winner",
    "mvp", "rookie", "draft", "trade", "transfer",

    # Football / Soccer
    "football", "soccer", "fifa", "world cup", "Euro 2020", "Euro 2024", "africa cup",
    "asia cup", "copa america", "uefa", "champions league",
    "europa league", "premier league", "la liga", "bundesliga",
    "serie a", "ligue 1", "mls", "fa cup", "carabao cup",
    "ucl", "goal", "striker", "midfielder", "defender",
    "goalkeeper", "penalty", "hat trick", 

    # Football players
    "messi", "ronaldo", "mbappe", "haaland", "neymar",
    "bellingham", "vinicius", "kane", "salah", "de bruyne",
    "modric", "lewandowski", "yamal",

    # Football clubs
    "real madrid", "barcelona", "manchester city",
    "manchester united", "liverpool", "arsenal", "chelsea",
    "tottenham", "bayern", "psg", "juventus", "inter",
    "milan", "dortmund", "atletico madrid", "ajax",
    "benfica", "porto", "napoli", "roma", "lazio",
    "newcastle", "aston villa", "west ham", "brighton",
    "rb leipzig", "leverkusen", "galatasaray",
    "fenerbahce", "sporting cp", "celtic",
    "rangers", "sevilla", "valencia",

    # American Football
    "nfl", "super bowl", "touchdown", "quarterback",
    "wide receiver", "running back", "field goal",

    # NFL players
    "patrick mahomes", "lamar jackson", "josh allen",
    "dak prescott", "aaron rodgers", "tom brady",
    "burrow", "joe burrow", "justin herbert",
    "travis kelce", "cmc", "christian mccaffrey",
    "brock purdy", "trevor lawrence",
    "saquon barkley", "micah parsons",    

    # NFL teams
    "chiefs", "49ers", "cowboys", "eagles", "packers",
    "patriots", "steelers", "ravens", "bills", "jets",
    "dolphins", "bengals", "lions", "vikings", "seahawks",
    "raiders", "saints", "giants", "chargers", "broncos",


    # NBA / Basketball
    "nba", "basketball", "wnba", "slam dunk",
    "three pointer", "play in", "eastern conference",
    "western conference", 
    
    # NBA players
    "lebron", "lebron james",
    "stephen curry", "curry", "durant", "giannis",
    "jokic", "luka doncic", "tatum", "wembanyama",
    "kobe", "shaq", "mj", "michael jordan", 
    "anthony davis", "booker", "devin booker",
    "ja morant", "anthony edwards",
    "kawhi leonard", "paul george",
    "embiid", "joel embiid",
    "brunson", "jalen brunson",
    "donovan mitchell",

    # NBA teams
    "lakers", "warriors", "celtics", "bucks", "heat",
    "knicks", "nets", "bulls", "spurs", "mavericks",
    "nuggets", "thunder", "76ers", "cavaliers",
    "clippers", "grizzlies", "hawks", "hornets",
    "jazz", "kings", "magic", "pelicans",
    "pistons", "raptors", "rockets", "suns",
    "timberwolves", "trail blazers", "wizards",


    # Baseball
    "mlb", "baseball", "world series", "home run",
    "pitcher", "batting", "yankees", "dodgers",
    "red sox", "mets", "shohei ohtani", "judge",

    # MLB players
    "aaron judge", "juan soto",
    "mookie betts", "freeman",
    "bryce harper", "tatis",
    "ronald acuna", "gerrit cole",

    # MLB teams
    "astros", "braves", "cubs", "guardians",
    "mariners", "orioles", "padres", "phillies",
    "pirates", "rays", "reds", "tigers",
    "twins", "white sox", "blue jays",


    # Hockey
    "nhl", "hockey", "stanley cup", "goalie",
    "oilers", "rangers", "maple leafs", "bruins",

    # NHL teams
    "avalanche", "canadiens", "canucks", "devils",
    "flames", "golden knights", "hurricanes",
    "islanders", "jets hockey", "kings hockey",
    "kraken", "panthers", "penguins", "predators",
    "senators", "sharks", "stars", "wild",

    # NHL players
    "mcdavid", "connor mcdavid",
    "auston matthews", "sidney crosby",
    "ovechkin", "alex ovechkin",
    "nathan mackinnon",


    # Tennis
    "tennis", "atp", "wta", "grand slam",
    "wimbledon", "us open", "french open",
    "australian open", "roland garros",
    
    # Tennis players
    "djokovic", "nadal", "federer", "alcaraz",
    "sinner", "swiatek", "gauff", "medvedev",
    "zverev", "tsitsipas",
    "rublev", "ruud",
    "sabalenka", "rybakina",
    "osaka", "raducanu",


    # Golf
    "golf", "pga", "masters", "us masters",
    "ryder cup", 
    
    # Golf players
    "jon rahm", "dechambeau",
    "koepka", "xander schauffele",
    "tiger woods", "mcilroy",
    "scheffler",


    # MMA / Boxing
    "ufc", "mma", "boxing", "boxer", "heavyweight",
    "knockout", "ko", "octagon", "pay per view",
    
    # MMA / Boxing
    "mcgregor", "jon jones", "adesanya",
    "canelo", "fury", "usyk", "jake paul",
    "islam makhachev", "alex pereira",
    "sean o'malley", "max holloway",
    "tank davis", "anthony joshua",


    # Formula 1 / Motorsport
    "f1", "formula 1", "formula one", "grand prix",
    "pole position", 
    
    # Formula 1
    "piastri", "george russell",
    "carlos sainz", "alonso",
    "sergio perez"
    "verstappen", "hamilton",
    "leclerc", "norris", "ferrari", "red bull",
    "mercedes", "mclaren",

    # Olympics
    "olympics", "olympic", "gold medal",
    "silver medal", "bronze medal",

    # Cricket
    "cricket", "ipl", "ashes", "t20",

    # Wrestling
    "wwe", "wrestling", "royal rumble",
    "wrestlemania", "roman reigns", "cody rhodes",

    # College sports
    "ncaa", "march madness", "college football",
    "college basketball", "heisman",
]

pattern = r"\b(?:" + "|".join(re.escape(word) for word in sports_keywords) + r")\b"

df_markets_small["sports"] = (
    df_markets_small["question"]
    .str.lower()
    .str.contains(pattern, regex=True, na=False)
    .astype(int)
)

In [155]:
# check the distribution of the new column sports

df_markets_small["sports"].value_counts()

sports
0    131488
1     51004
Name: count, dtype: int64

In [156]:
# create a new column "esports" that is 1 if the question contains any of the esports keywords, otherwise 0

esports_keywords = [

    # General esports terms
    "esports", "e-sports", "gaming", "gamer",
    "tournament", "major", "world championship",
    "playoffs", "grand final", "best of", "bo3", "bo5",

    #console_keywords
    "playstation", "ps5", "ps4",
    "xbox", "xbox series x",
    "nintendo switch",
    "steam deck"


    # Counter-Strike
    "cs", "cs2", "csgo", "counter strike",
    "blast", "iem", "esl", "pgl", "faceit",
    "hltv", "frag", "ace", "clutch",

    # CS players & teams
    "s1mple", "zywoo", "donk", "device", "niko",
    "faze", "g2", "navi", "vitality", "spirit",
    "liquid", "mouz", "astralis",

    # League of Legends
    "league of legends", "lol", "lck", "lec",
    "lcs", "msi", "worlds", "summoner's cup",
    "riot games", "faker", "t1", "geng",
    "fnatic", "g2 esports", "jdg", "blg",

    # Dota 2
    "dota", "dota 2", "the international",
    "ti", "ancient", "valve",
    "team spirit", "liquid dota", "og",

    # Valorant
    "valorant", "vct", "radiant",
    "sentinels", "paper rex", "fnatic valorant",
    "loud", "derke", "tenz",

    # Fortnite
    "fortnite", "fortnite world cup",
    "epic games", "bugha",

    # Call of Duty
    "cod", "call of duty", "warzone",
    "cdl", "optic", "faze clan",

    # Overwatch
    "overwatch", "overwatch league", "owl",

    # Rocket League
    "rocket league", "rlcs",

    # Apex Legends
    "apex", "apex legends", "algs",

    # Rainbow Six
    "rainbow six", "r6", "siege",

    # PUBG
    "pubg", "pubg mobile",

    # StarCraft
    "starcraft", "sc2",

    # Fighting games
    "street fighter", "tekken", "smash",
    "super smash bros", "evo",

    # Mobile esports
    "mobile legends", "free fire",

    # Organizations
    "faze clan", "100 thieves", "cloud9",
    "team liquid", "tsm", "nrg", "optic",
    "sentinels", "fnatic", "g2 esports"
]

pattern = r"\b(?:" + "|".join(re.escape(word) for word in esports_keywords) + r")\b"

df_markets_small["esports"] = (
    df_markets_small["question"]
    .str.lower()
    .str.contains(pattern, na=False)
    .astype(int)
)

In [157]:
# check the distribution of the new column esports

df_markets_small["esports"].value_counts()

esports
0    176355
1      6137
Name: count, dtype: int64

In [158]:
# create a new column "crypto" that is 1 if the question contains any of the crypto keywords, otherwise 0

crypto_keywords = [

    # General crypto terms
    "crypto", "cryptocurrency", "blockchain","EIP-1559",
    "web3", "onchain", "defi", "cefi",
    "token", "tokens", "coin", "coins",
    "stablecoin", "staking", "validator",
    "smart contract", "wallet", "cold wallet",
    "hot wallet", "seed phrase", "gas fee",

    # Major cryptocurrencies
    "bitcoin", "btc", "ethereum", "eth",
    "solana", "sol", "xrp", "ripple",
    "cardano", "ada", "dogecoin", "doge",
    "litecoin", "ltc", "tron", "trx",
    "avalanche", "avax", "polkadot", "dot",
    "chainlink", "link", "monero", "xmr",

    # Exchanges
    "binance", "coinbase", "kraken",
    "bybit", "okx", "kucoin", "bitfinex",

    # DeFi protocols
    "uniswap", "aave", "curve", "makerdao",
    "compound", "lido", "pancakeswap",

    # NFTs
    "nft", "nfts", "bored ape",
    "cryptopunk", "opensea",

    # Meme coins
    "memecoin", "meme coin",
    "pepe", "shiba inu", "shib",
    "floki", "bonk",

    # Trading / market structure
    "airdrop", "halving", "burn",
    "mint", "yield farming", "liquidity pool",
    "dex", "amm", "bridge", "layer 2",
    "mainnet", "testnet",

    # Regulation / crypto-specific events
    "spot etf", "bitcoin etf",
    "crypto etf", "sec crypto",
    "token unlock",

    # Companies / ecosystems strongly tied to crypto
    "tether", "usdt", "usdc",
    "metamask", "phantom wallet",

    # Crypto founders / figures
    "satoshi", "vitalik", "cz",
    "sam bankman fried", "sbf"
]

pattern = r"\b(?:" + "|".join(re.escape(word) for word in crypto_keywords) + r")\b"

df_markets_small["crypto"] = (
    df_markets_small["question"]
    .str.lower()
    .str.contains(pattern, na=False)
    .astype(int)
)

In [159]:
# check the distribution of the new column crypto

df_markets_small["crypto"].value_counts()

crypto
0    119319
1     63173
Name: count, dtype: int64

In [160]:
# create a new column "finance" that is 1 if the question contains any of the finance keywords, otherwise 0

finance_keywords = [

    # General finance terms
    "finance", "financial market", "capital market",
    "asset", "assets", "liability", "equity",
    "portfolio", "hedge fund", "private equity",
    "venture capital", "investment", "investor",

    # Macroeconomics
    "inflation", "deflation", "recession",
    "gdp", "cpi", "ppi", "unemployment",
    "interest rate", "rate cut", "rate hike",
    "economic growth", "soft landing",
    "hard landing", "minimum wage", "jobless",

    # Central banks
    "fed", "federal reserve", "ecb",
    "central bank", "fomc",
    "jerome powell", "lagarde",

    # Stock market
    "stock market", "stocks", "share price",
    "equities", "bull market", "bear market",
    "market cap", "volatility",

    # Indices
    "s&p 500", "nasdaq", "dow jones",
    "russell 2000", "dax", "nikkei",

    # Bonds / fixed income
    "bond", "bonds", "treasury",
    "yield", "yield curve",
    "credit spread",

    # Commodities
    "oil", "brent", "wti",
    "gold", "silver", "natural gas",

    # Forex
    "forex", "fx", "usd", "eur",
    "yen", "exchange rate", "currency market",

    # Banking
    "bank", "banking", "commercial bank",
    "investment bank", "liquidity crisis",
    "bank run", "default",

    # Trading / derivatives
    "options", "futures", "derivatives",
    "short selling", "margin call",
    "etf", "index fund",

    # Corporate finance
    "earnings", "revenue", "profit",
    "eps", "dividend", "buyback",
    "valuation", "cash flow",
    "balance sheet"
]

pattern = r"\b(?:" + "|".join(re.escape(word) for word in finance_keywords) + r")\b"

df_markets_small["finance"] = (
    df_markets_small["question"]
    .str.lower()
    .str.contains(pattern, na=False)
    .astype(int)
)

In [161]:
# check the distribution of the new column finance

df_markets_small["finance"].value_counts()

finance
0    178504
1      3988
Name: count, dtype: int64

In [162]:
# create a new column "business" that is 1 if the question contains any of the business keywords, otherwise 0

business_keywords = [

    # General business terms
    "business", "company", "corporation", "firm",
    "enterprise", "startup", "founder", "cofounder",
    "ceo", "cfo", "board of directors", "sell", "acquire", "invest", "investor",
    "shareholder", "stakeholder", "price", "valuation", "funding", "revenue", "profit",
    "loss", "growth", "expansion", "layoff", "hiring", "partnership", "auction",
    "acquired",

    # Corporate events
    "merger", "acquisition", "takeover",
    "m&a", "buyout", "spin off", "ipo",
    "bankruptcy", "chapter 11", "restructuring",
    "layoffs", "downsizing",

    # Financial reporting
    "earnings", "quarterly earnings",
    "annual report", "guidance",
    "revenue", "sales", "profit",
    "operating income", "ebitda",
    "cash flow", "margin",

    # Valuation / ownership
    "valuation", "market value",
    "private equity", "venture capital",
    "funding round", "series a",
    "series b", "series c",

    # Business operations
    "supply chain", "manufacturing",
    "production", "factory", "logistics",
    "distribution", "retailer",

    # Tech companies
    "apple", "microsoft", "google",
    "alphabet", "amazon", "meta",
    "tesla", "nvidia", "openai",
    "anthropic", "xai", "spacex",

    # Financial companies
    "blackrock", "goldman sachs",
    "jp morgan", "morgan stanley",
    "citigroup", "bank of america",

    # Consumer companies
    "netflix", "disney", "nike",
    "coca cola", "mcdonalds",
    "starbucks", "uber", "airbnb",

    # Automotive / industrial
    "toyota", "ford", "gm",
    "volkswagen", "bmw", "mercedes",
    "boeing", "airbus",

    # Business actions
    "partnership", "joint venture",
    "contract", "deal", "agreement",
    "expansion", "market share",
    "competition", "monopoly",

    # AI / tech business terms
    "ai company", "chipmaker",
    "semiconductor", "data center",
    "cloud business"
]

pattern = r"\b(?:" + "|".join(re.escape(word) for word in business_keywords) + r")\b"

df_markets_small["business"] = (
    df_markets_small["question"]
    .str.lower()
    .str.contains(pattern, na=False)
    .astype(int)
)

In [163]:
# check the distribution of the new column business

df_markets_small["business"].value_counts()

business
0    160528
1     21964
Name: count, dtype: int64

In [164]:
# create a new column "technology_ai" that is 1 if the question contains any of the technology/ai keywords, otherwise 0

technology_ai_keywords = [

    # General technology terms
    "technology", "tech", "software",
    "hardware", "platform", "operating system",
    "app", "application", "device",

    # Artificial intelligence
    "artificial intelligence", "ai",
    "generative ai", "agi",
    "machine learning", "deep learning",
    "neural network", "large language model",
    "llm", "multimodal",

    # AI tools / models
    "chatgpt", "gpt-4", "gpt-5",
    "claude", "gemini", "copilot",
    "midjourney", "sora",

    # AI companies
    "openai", "anthropic", "deepmind",
    "xai", "stability ai",

    # AI infrastructure
    "gpu", "h100", "blackwell",
    "cuda", "training model",
    "inference", "compute",

    # Chips / semiconductors
    "semiconductor", "chip", "chipmaker",
    "microchip", "processor",

    # Robotics / automation
    "robot", "robotics", "humanoid robot",
    "automation", "autonomous",

    # Consumer tech
    "iphone", "android", "ios",
    "smartphone", "wearable",
    "smart glasses",

    # Internet / digital
    "search engine", "social media",
    "streaming platform", "cloud computing",
    "saas",

    # Emerging tech
    "virtual reality", "vr",
    "augmented reality", "ar",
    "mixed reality", "quantum computing",
    "self driving", "autonomous driving",

    # Cybersecurity
    "cybersecurity", "cyber attack",
    "hacker", "data breach",

    # Tech actions
    "product launch", "beta release",
    "software update", "api",
    "open source"
]

pattern = r"\b(?:" + "|".join(re.escape(word) for word in technology_ai_keywords) + r")\b"

df_markets_small["technology_ai"] = (
    df_markets_small["question"]
    .str.lower()
    .str.contains(pattern, na=False)
    .astype(int)
)

In [165]:
# check the distribution of the new column technology_ai

df_markets_small["technology_ai"].value_counts()

technology_ai
0    180798
1      1694
Name: count, dtype: int64

In [166]:
# create a new column "geopolitics" that is 1 if the question contains any of the geopolitics keywords, otherwise 0

geopolitics_keywords = [

    # Wars / conflicts
    "war", "invasion", "military conflict",
    "armed conflict", "ceasefire",
    "peace deal", "troops", "airstrike",
    "missile strike", "drone strike",
    "offensive", "counteroffensive",

    # International relations
    "diplomatic relations", "foreign policy",
    "sanctions", "trade sanctions",
    "embassy", "ambassador",
    "peace talks", "summit meeting",

    # Alliances / international organizations
    "nato", "united nations", "un security council",
    "g7", "g20", "brics",

    # Geopolitical hotspots
    "ukraine", "russia ukraine",
    "taiwan strait", "south china sea",
    "gaza", "west bank", "kashmir",

    # Countries frequently tied to geopolitical markets
    "russia", "ukraine", "china",
    "taiwan", "iran", "israel",
    "north korea", "south korea",
    "syria",

    # Military / defense
    "military", "defense ministry",
    "nuclear weapon", "nuclear test",
    "ballistic missile", "warship",
    "fighter jet", "mobilization",

    # Territorial / sovereignty issues
    "territory", "border dispute",
    "annexation", "occupation",
    "sovereignty", "independence movement",

    # Energy geopolitics
    "oil embargo", "gas pipeline",
    "energy crisis",

    # Cyber / intelligence
    "cyber warfare", "espionage",
    "spy agency", "intelligence operation",

    # Geopolitical leaders strongly tied to global conflicts
    "zelensky", "putin", "xi jinping",
    "netanyahu", "kim jong un"
]

pattern = r"\b(?:" + "|".join(re.escape(word) for word in geopolitics_keywords) + r")\b"

df_markets_small["geopolitics"] = (
    df_markets_small["question"]
    .str.lower()
    .str.contains(pattern, na=False)
    .astype(int)
)

In [167]:
# check the distribution of the new column geopolitics

df_markets_small["geopolitics"].value_counts()

geopolitics
0    179409
1      3083
Name: count, dtype: int64

In [168]:
# create a new column "culture" that is 1 if the question contains any of the culture keywords, otherwise 0

culture_keywords = [


    # General entertainment / culture
    "celebrity", "pop culture",
    "entertainment", "viral",
    "red carpet","art",

    # Movies / TV
    "movie", "film", "tv show",
    "series", "season finale",
    "box office", "streaming",
    "netflix series", "hollywood",

    # Awards
    "oscars", "academy awards",
    "golden globes", "emmys",
    "grammys", "bafta",

    # Music
    "album", "single", "music video",
    "concert", "tour", "world tour",
    "billboard", "spotify",

    # Artists / celebrities
    "taylor swift", "drake",
    "kanye west", "beyonce",
    "rihanna", "dua lipa",
    "billie eilish", "the weeknd",
    "justin bieber", "selena gomez",
    "bezos", "musk",

    # Actors / public figures
    "leonardo dicaprio",
    "zendaya", "timothee chalamet",
    "kim kardashian",

    # Social media / creators
    "influencer", "youtuber",
    "tiktok", "instagram",
    "viral video","twitter","tweets","subscriber","subscribers",

    # Events
    "met gala", "eurovision",
    "super bowl halftime show",

    # Fashion / lifestyle
    "fashion week", "runway",
    "luxury brand","designer", "gucci", "louis vuitton","jordan"
]

pattern = r"\b(?:" + "|".join(re.escape(word) for word in culture_keywords) + r")\b"

df_markets_small["culture"] = (
    df_markets_small["question"]
    .str.lower()
    .str.contains(pattern, na=False)
    .astype(int)
)

In [169]:
# check the distribution of the new column culture

df_markets_small["culture"].value_counts()

culture
0    177325
1      5167
Name: count, dtype: int64

In [170]:
# create a new column "science" that is 1 if the question contains any of the science keywords, otherwise 0

science_keywords = [

    # Health / diseases
    "covid", "coronavirus", "pandemic",
    "epidemic", "outbreak", "virus",
    "vaccine", "vaccination",
    "disease", "infection",

    # Public health
    "world health organization",
    "cdc", "public health",

    # Weather / climate
    "weather", "temperature",
    "heatwave", "cold wave",
    "storm", "hurricane", "typhoon",
    "tornado", "flood", "wildfire",
    "earthquake", "volcano", "CO2",

    # Climate / environment
    "climate change", "global warming",
    "el nino", "la nina",
    "carbon emissions",

    # Space / astronomy
    "nasa", "spacex launch",
    "rocket launch", "moon mission",
    "mars mission", "satellite",
    "asteroid", "solar eclipse",

    # Science / technology research
    "scientist", "research study",
    "scientific breakthrough",
    "clinical trial",

    # Biotechnology
    "biotech", "gene editing",
    "crispr"
]

pattern = r"\b(?:" + "|".join(re.escape(word) for word in science_keywords) + r")\b"

df_markets_small["science"] = (
    df_markets_small["question"]
    .str.lower()
    .str.contains(pattern, na=False)
    .astype(int)
)

In [171]:
# check the distribution of the new column science

df_markets_small["science"].value_counts()

science
0    177477
1      5015
Name: count, dtype: int64

In [172]:
# markets that do not belong to any category

no_category = df_markets_small[
    (
        df_markets_small["politics"] +
        df_markets_small["sports"] +
        df_markets_small["esports"] +
        df_markets_small["crypto"] +
        df_markets_small["finance"] +
        df_markets_small["business"] +
        df_markets_small["technology_ai"] +
        df_markets_small["geopolitics"] +
        df_markets_small["culture"] +
        df_markets_small["science"]
    ) == 0
]

# number of uncategorized markets
print(len(no_category))

36081

In [173]:
pd.set_option("display.max_colwidth", None)

no_category["question"].head(25)

39                                        Will indoor dining be prohibited in NYC at any point before 2021?
79                                             Who will the world's richest person be on February 27, 2021?
85                                                              $2000 stimulus checks by February 28, 2021?
92                                              Will YFI total supply be greater than 30,000 by March 15th?
106                                                    Will Robinhood allow buying of $GME on February 2nd?
161                                                          Will EIP-1559 be implemented by July 31, 2021?
196                                          Will daily atmospheric CO2 be above 418 ppm on March 22, 2021?
198                                                  Will Texas reinstate a mask mandate by April 11, 2021?
206                                          Will American mask usage be 75% or higher on April 14th, 2021?
212                                       Will daily atmospheric CO2 be above 418.25 ppm on March 23, 2021?
215    Will more than 1.75 million people travel through a TSA checkpoint on any day on or before April 10?
219                                       Will the Ever Given be dislodged from the Suez Canal by March 30?
223                                                    How many charges will Derek Chauvin be convicted of?
229                             Will Matt Gaetz continue to hold Congressional office through June 1, 2021?
240       Will more than 1.75 million people travel through a TSA checkpoint on any day on or before May 1?
262                           Will the Ever Given exit the Great Bitter Lake in the Suez Canal by April 22?
280                             Will the Ever Given exit the Great Bitter Lake in the Suez Canal by May 20?
305                                                      Will $MATIC (Polygon) be above $1 on May 20, 2021?
306                                         Will Rudy Giuliani be indicted for a federal crime by August 1?
308                                                                        Will NYC fully reopen by July 1?
309      Will more than 1.75 million people travel through a TSA checkpoint on any day on or before May 25?
312                     Will LeVar Burton be announced as the next permanent host of Jeopardy by August 15?
353      Will more than 2.25 million people travel through a TSA checkpoint on any day on or before June 1?
358       Will A Quiet Place Part II gross more domestically on opening weekend than A Quiet Place Part I?
359                                               Will Patricio O'Ward have a top 3 finish at the Indy 500?
Name: question, dtype: object

In [174]:
# check if the new variables work

import pandas as pd

# show full text without truncation
pd.set_option("display.max_colwidth", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)

# display selected columns
df_markets_small[
    ["question", "politics", "sports", "esports", "crypto", "finance", "business", "technology_ai", "geopolitics", "culture", "science"]
].head(25)

,question,politics,sports,esports,crypto,finance,business,technology_ai,geopolitics,culture,science
0,Will Joe Biden get Coronavirus before the election?,1,0,0,0,0,0,0,0,0,1
1,"Will Airbnb begin publicly trading before Jan 1, 2021?",0,0,0,0,0,1,0,0,0,0
2,"Will a new Supreme Court Justice be confirmed before Nov 3rd, 2020?",1,0,0,0,0,0,0,0,0,0
3,"Will Kim Kardashian and Kanye West divorce before Jan 1, 2021?",0,0,0,0,0,0,0,0,1,0
4,"Will Coinbase begin publicly trading before Jan 1, 2021?",0,0,0,1,0,0,0,0,0,0
5,"What will the price of Bitcoin be on November 4th, 2020?",0,0,0,1,0,1,0,0,0,0
6,Will Trump win the 2020 U.S. presidential election?,1,0,0,0,0,0,0,0,0,0
7,Will there be an Emergency Use Authorization (EUA) granted for a COVID-19 vaccine prior to Nov 3 2020?,0,0,0,0,0,0,0,0,0,1
8,"What will the total value locked (TVL) in DeFi be at the end of 2020, according to DefiPulse?",0,0,0,1,0,0,0,0,0,0
9,"What will the USD price of Filecoin ($FIL) be on November 17th, 2020?",0,0,0,0,1,1,0,0,0,0
10,Will Drake release a new studio album before the end of 2020?,0,0,0,0,0,0,0,0,1,0
11,Which party will win Florida in the 2020 presidential election?,1,0,0,0,0,0,0,0,0,0
12,How many confirmed Coronavirus cases will there be at EOY in the USA?,0,0,0,0,0,0,0,0,0,1
13,Who will win the 2020 MLB World Series?,0,1,0,0,0,0,0,0,1,0
14,Will Dharma’s Phase 1 Retroactive UNI Distribution proposal pass?,0,0,0,0,0,1,0,0,0,0
15,Will there be a federal charge filed against Hunter Biden before 2021?,1,0,0,0,0,0,0,0,0,0
16,Will BTC break $15k before 2021?,0,0,0,1,0,0,0,0,0,0
17,Will Khabib win his UFC 254 Fight?,0,1,0,0,0,0,0,0,0,0
18,Will 538 outperform The Economist in forecasting the 2020 Presidential Election?,1,0,0,0,0,0,0,0,0,0
19,Who will win the 2020 League of Legends World Championship?,0,1,1,0,0,0,0,0,0,0
20,Which party will win Pennsylvania in the 2020 presidential election?,1,0,0,0,0,0,0,0,0,0
21,Which party will win Texas in the 2020 presidential election?,1,0,0,0,0,0,0,0,0,0
22,Which party will win North Carolina in the 2020 presidential election?,1,0,0,0,0,0,0,0,0,0
23,Which party will win Georgia in the 2020 presidential election?,1,0,0,0,0,0,0,0,0,0
24,Which party will win Arizona in the 2020 Presidential Election?,1,0,0,0,0,0,0,0,0,0

## 4.3 number of categories

In [175]:
# create a column with the number of categories each market belongs to

category_columns = [
    "politics",
    "sports",
    "esports",
    "crypto",
    "finance",
    "business",
    "technology_ai",
    "geopolitics",
    "culture",
    "science"
]

df_markets_small["number_of_categories"] = (
    df_markets_small[category_columns]
    .sum(axis=1)
)

In [176]:
# check if the variable was created correctly

df_markets_small[
    [
        "question",
        "politics",
        "sports",
        "esports",
        "crypto",
        "finance",
        "business",
        "technology_ai",
        "geopolitics",
        "culture",
        "science",
        "number_of_categories"
    ]
].head(10)

,question,politics,sports,esports,crypto,finance,business,technology_ai,geopolitics,culture,science,number_of_categories
0,Will Joe Biden get Coronavirus before the election?,1,0,0,0,0,0,0,0,0,1,2
1,"Will Airbnb begin publicly trading before Jan 1, 2021?",0,0,0,0,0,1,0,0,0,0,1
2,"Will a new Supreme Court Justice be confirmed before Nov 3rd, 2020?",1,0,0,0,0,0,0,0,0,0,1
3,"Will Kim Kardashian and Kanye West divorce before Jan 1, 2021?",0,0,0,0,0,0,0,0,1,0,1
4,"Will Coinbase begin publicly trading before Jan 1, 2021?",0,0,0,1,0,0,0,0,0,0,1
5,"What will the price of Bitcoin be on November 4th, 2020?",0,0,0,1,0,1,0,0,0,0,2
6,Will Trump win the 2020 U.S. presidential election?,1,0,0,0,0,0,0,0,0,0,1
7,Will there be an Emergency Use Authorization (EUA) granted for a COVID-19 vaccine prior to Nov 3 2020?,0,0,0,0,0,0,0,0,0,1,1
8,"What will the total value locked (TVL) in DeFi be at the end of 2020, according to DefiPulse?",0,0,0,1,0,0,0,0,0,0,1
9,"What will the USD price of Filecoin ($FIL) be on November 17th, 2020?",0,0,0,0,1,1,0,0,0,0,2

In [177]:
# have a look at the distribution of the new variable
df_markets_small["number_of_categories"].value_counts()

number_of_categories
1    117703
0     36081
2     28075
3       610
4        23
Name: count, dtype: int64

In [178]:
# have a look at markets that belong to 4 categories

df_markets_small.loc[
    df_markets_small["number_of_categories"] == 4,
    [
        "question",
        "politics",
        "sports",
        "esports",
        "crypto",
        "finance",
        "business",
        "technology_ai",
        "geopolitics",
        "culture",
        "science",
        "number_of_categories"
    ]
].head(10)

,question,politics,sports,esports,crypto,finance,business,technology_ai,geopolitics,culture,science,number_of_categories
758,Will a Crypto Twitter Fish win the CryptOG Charity Poker Tournament?,0,1,1,1,0,0,0,0,1,0,4
7508,Will any Friend Tech user's share price be >5 ETH by Friday?,0,0,0,1,1,1,1,0,0,0,4
7509,Will Faze Banks’ share price be >10 ETH this month?,0,0,1,1,1,1,0,0,0,0,4
8862,"$BTC price <$40,000 1 hour after ETF approval?",1,0,0,1,1,1,0,0,0,0,4
8863,"$BTC price between $42,500-45,000 1 hour after ETF approval?",1,0,0,1,1,1,0,0,0,0,4
8864,"$BTC price between $40,000-42,500 1 hour after ETF approval?",1,0,0,1,1,1,0,0,0,0,4
8865,"$BTC price between $47,500-50,000 1 hour after ETF approval?",1,0,0,1,1,1,0,0,0,0,4
8866,"$BTC price >$50,000 1 hour after ETF approval?",1,0,0,1,1,1,0,0,0,0,4
8867,"$BTC price between $45,000-47,500 1 hour after ETF approval?",1,0,0,1,1,1,0,0,0,0,4
34297,Will Ukraine qualify for the Eurovision 2025 grand final?,0,1,1,0,0,0,0,1,1,0,4

## 4.3 outcomes

In [179]:
# create dummy variables for the 3 most common outcome types in the "outcomes" column, and a dummy variable for all other outcome types

# Yes / No
df_markets_small["outcome_yes_no"] = (
    df_markets_small["outcomes"] == '["Yes", "No"]'
).astype(int)

# Up / Down
df_markets_small["outcome_up_down"] = (
    df_markets_small["outcomes"] == '["Up", "Down"]'
).astype(int)

# Over / Under
df_markets_small["outcome_over_under"] = (
    df_markets_small["outcomes"] == '["Over", "Under"]'
).astype(int)

# Other
df_markets_small["outcome_other"] = (
    ~df_markets_small["outcomes"].isin([
        '["Yes", "No"]',
        '["Up", "Down"]',
        '["Over", "Under"]'
    ])
).astype(int)

# test
df_markets_small[
    ["outcome_yes_no", "outcome_up_down", "outcome_over_under", "outcome_other"]
].sum()

outcome_yes_no        94789
outcome_up_down       41878
outcome_over_under    12524
outcome_other         33301
dtype: int64

## 4.4 Market Uncertainty

The uncertainty measure is calculated as:

Uncertainty = 1 - |p_1 - p_2|

where \(p_1\) and \(p_2\) are the probabilities of the two outcomes.

The measure ranges from 0 to 1:

- Uncertainty = 1: Maximum uncertainty (50% vs. 50%)
- Uncertainty = 0: No uncertainty (100% vs. 0%)

Therefore, higher values indicate that the market is more uncertain about the outcome, while lower values indicate a stronger market consensus.

Markets with more than two outcomes (40 observations, 0.02% of the sample) were assigned missing values (`NaN`) because the uncertainty measure is designed for binary markets only.

In [180]:
# create a new variable uncertainty

import ast
import numpy as np

def calculate_uncertainty(x):
    probs = [float(i) for i in ast.literal_eval(x)]

    if len(probs) != 2:
        return np.nan

    return 1 - abs(probs[0] - probs[1])

df_markets_small["uncertainty"] = (
    df_markets_small["outcomePrices"]
    .apply(calculate_uncertainty)
)

# Test
df_markets_small[["outcomePrices", "uncertainty"]].head()

,outcomePrices,uncertainty
0,"[""0"", ""0""]",1.000000
1,"[""0"", ""0""]",1.000000
2,"[""0"", ""0""]",1.000000
3,"[""0.000001011082052522541417308141468657552"", ""0.9999989889179474774585826918585313""]",0.000002
4,"[""0.000001024519509568169644816863666886675"", ""0.9999989754804904318303551831363331""]",0.000002

In [181]:
df_markets_small["uncertainty"].describe()

count    182452.000000
mean          0.003164
std           0.055496
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: uncertainty, dtype: float64

In [182]:
# how many markets have uncertainty between 0,1 and 0,9?

int(
    ((df_markets_small["uncertainty"] >= 0.1) &
     (df_markets_small["uncertainty"] <= 0.9)).sum()
)

57

Only 57 out of 182.452 Markets have a uncertainty between 10% and 90%. I assume this is the case because the events are closing when the event is nearly done and the outcomePrices the outcome is clear.

# 4.5 Market Duration

In [183]:
# create a new variable duration that is the number of days between the start and end date of the market
df_markets_small["duration"] = (
    df_markets_small["endDateIso"] - df_markets_small["startDateIso"]
).dt.days

# set negative durations to NaN
df_markets_small.loc[
    df_markets_small["duration"] < 0,
    "duration"
] = pd.NA

# Test
df_markets_small["duration"].describe()

count    175049.000000
mean         21.180795
std          56.813004
min           0.000000
25%           1.000000
50%           4.000000
75%          10.000000
max        1031.000000
Name: duration, dtype: float64

In [184]:
# Remove markets with missing duration
df_markets_small = df_markets_small.dropna(subset=["duration"])

In [185]:
# test
len(df_markets_small)

175049

# 4.6 rewardsMinSize Dummy

In [186]:
# Reward dummy: Equals 1 if the market has a positive minimum reward (rewardsMinSize > 0), 
# and 0 if no minimum reward is offered (rewardsMinSize = 0).

df_markets_small["reward_dummy"] = (df_markets_small["rewardsMinSize"] > 0).astype(int)

# test
df_markets_small["reward_dummy"].value_counts()

reward_dummy
0    132091
1     42958
Name: count, dtype: int64

In [187]:
df_markets_small.info()

<class 'pandas.core.frame.DataFrame'>
Index: 175049 entries, 98 to 199999
Data columns (total 32 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   id                    175049 non-null  int64
 1   question              175049 non-null  object
 2   startDateIso          175049 non-null  datetime64[ns]
 3   endDateIso            175049 non-null  datetime64[ns]
 4   volume                175049 non-null  float64
 5   liquidity             44504 non-null   float64
 6   outcomes              175049 non-null  object
 7   outcomePrices         175049 non-null  object
 8   rewardsMinSize        175049 non-null  float64
 9   restricted            175049 non-null  int64
 10  spread_poly           175049 non-null  float64
 11  bestBid               81596 non-null   float64
 12  bestAsk               175035 non-null  float64
 13  spread                81583 non-null   float64
 14  politics              175049 non-null  int64
 15  sports                175049 non-null  int64
 16  esports               175049 non-null  int64
 17  crypto                175049 non-null  int64
 18  finance               175049 non-null  int64
 19  business              175049 non-null  int64
 20  technology_ai         175049 non-null  int64
 21  geopolitics           175049 non-null  int64
 22  culture               175049 non-null  int64
 23  science               175049 non-null  int64
 24  number_of_categories  175049 non-null  int64
 25  outcome_yes_no        175049 non-null  int64
 26  outcome_up_down       175049 non-null  int64
 27  outcome_over_under    175049 non-null  int64
 28  outcome_other         175049 non-null  int64
 29  uncertainty           175042 non-null  float64
 30  duration              175049 non-null  float64
 31  reward_dummy          175049 non-null  int64
dtypes: datetime64[ns](2), float64(9), int64(18), object(3)
memory usage: 44.1+ MB

# 5. save final dataframe

In [188]:
# Save the cleaned DataFrame as a CSV file for further analysis
df_markets_small.to_csv("polymarkets_data_cleaned.csv", index=False)